services:
  postgres:
    image: postgres:16
    container_name: traffic-postgres
    environment:
      POSTGRES_USER: traffic
      POSTGRES_PASSWORD: traffic
      POSTGRES_DB: traffic
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: