alter table traffic_sample
    add column if not exists flow_provider varchar(64),
    add column if not exists flow_product varchar(128),
    add column if not exists flow_source_zoom integer,
    add column if not exists flow_requested_cadence_seconds integer,
    add column if not exists incident_provider varchar(64),
    add column if not exists incident_product varchar(128),
    add column if not exists incident_fetched_at timestamptz,
    add column if not exists incident_source_updated_at timestamptz,
    add column if not exists incident_requested_cadence_seconds integer;

alter table traffic_sample_archive
    add column if not exists flow_provider varchar(64),
    add column if not exists flow_product varchar(128),
    add column if not exists flow_source_zoom integer,
    add column if not exists flow_requested_cadence_seconds integer,
    add column if not exists incident_provider varchar(64),
    add column if not exists incident_product varchar(128),
    add column if not exists incident_fetched_at timestamptz,
    add column if not exists incident_source_updated_at timestamptz,
    add column if not exists incident_requested_cadence_seconds integer;

create or replace view traffic_sample_all as
select
    s.id as history_id,
    s.id as sample_ref_id,
    s.corridor,
    s.avg_current_speed,
    s.avg_freeflow_speed,
    s.min_current_speed,
    s.confidence,
    s.source_mode,
    s.speed_sample_count,
    s.speed_stddev,
    s.p10_speed,
    s.p50_speed,
    s.p90_speed,
    s.incident_count,
    s.incidents_json,
    s.validation_requested_points,
    s.validation_returned_points,
    s.validation_coverage_ratio,
    s.validation_used,
    s.degraded,
    s.degraded_reason,
    s.speed_state_signature,
    s.semantic_flow_signature,
    s.localized_slowdown,
    s.localized_slowdown_note,
    s.polled_at,
    s.ingested_at,
    cast(null as timestamptz) as archived_at,
    false as is_archived,
    s.flow_provider,
    s.flow_product,
    s.flow_source_zoom,
    s.flow_requested_cadence_seconds,
    s.incident_provider,
    s.incident_product,
    s.incident_fetched_at,
    s.incident_source_updated_at,
    s.incident_requested_cadence_seconds
from traffic_sample s
union all
select
    -a.source_id as history_id,
    a.source_id as sample_ref_id,
    a.corridor,
    a.avg_current_speed,
    a.avg_freeflow_speed,
    a.min_current_speed,
    a.confidence,
    a.source_mode,
    a.speed_sample_count,
    a.speed_stddev,
    a.p10_speed,
    a.p50_speed,
    a.p90_speed,
    a.incident_count,
    a.incidents_json,
    a.validation_requested_points,
    a.validation_returned_points,
    a.validation_coverage_ratio,
    a.validation_used,
    a.degraded,
    a.degraded_reason,
    a.speed_state_signature,
    a.semantic_flow_signature,
    a.localized_slowdown,
    a.localized_slowdown_note,
    a.polled_at,
    a.ingested_at,
    a.archived_at,
    true as is_archived,
    a.flow_provider,
    a.flow_product,
    a.flow_source_zoom,
    a.flow_requested_cadence_seconds,
    a.incident_provider,
    a.incident_product,
    a.incident_fetched_at,
    a.incident_source_updated_at,
    a.incident_requested_cadence_seconds
from traffic_sample_archive a;
